getsentry/devservices

.pre-commit-config.yaml, requirements.txt, setup.py, src/commands/list_dependencies.py, src/utils/config.py
This uses pydantic to implement a more rigorous structure for devservices configuration files
=> feat(config): Validation and typing for configuration file

src/configs/service_config.py
Got changed back in the shuffle
=> fix(config): Switching to x-sentry-service-config

src/commands/start.py, src/commands/stop.py, src/utils/docker_compose.py
Adds start/stop basic cli commands that use the services in the default mode.
=> feat(cli): Add start and stop

src/commands/logs.py, src/main.py
=> feat(cli): Add logs cli command

src/commands/status.py, src/main.py
Just a simple working thing for now
Looks like this:
=> feat(cli): Add status cli command

.github/workflows/test.yml, .gitignore, src/configs/service_config.py, tests/configs/test_service_config.py
Adding foundation for testing in this repo starting with basic tests for the service config
=> chore(service-config): Adding basic tests for service config

src/commands/logs.py, src/commands/start.py, src/commands/status.py, src/commands/stop.py, src/exceptions.py, src/utils/docker_compose.py
This change aims to gracefully deal with errors stemming from docker compose commands and provide meaningful responses to users.
=> fix(cli): Adding basic error handling to docker-compose commands

CHANGELOG.md, pyproject.toml
=> release: 0.0.1

.github/workflows/test.yml, pyproject.toml
=> feat(python): Support python 3.10

devservices/commands/status.py
=> feat(status): Add url

devservices/commands/logs.py, devservices/commands/start.py, devservices/commands/status.py, devservices/commands/stop.py, devservices/configs/service_config.py, devservices/constants.py, tests/commands/test_start.py, tests/commands/test_stop.py, tests/configs/test_service_config.py, tests/testutils.py
renames this to avoid confusion so people don't use docker compose
=> feat(config): Rename docker-compose.yml file to config.yml

devservices/main.py
=> feat(help): Clean up menu

.github/workflows/test.yml, requirements-dev.txt
Adding codecov for test coverage tracking
=> feat(codecov): Adding codecov

.envrc, .gitignore
this adds virtualenv for dev setup
=> chore(dev): Add virtualenv

codecov.yml
Not sure why it doesn't do this by default
=> Ignoring testing and tests for coverage

testing/utils.py
Updating usage of "devservices" directory to use the constant.
=> chore(utils): Updating usage to use a constant

devservices/commands/purge.py, devservices/main.py, tests/commands/test_purge.py
Fixes #71. Adds a new `purge` command that clears the user's local devservices cache.
=> feat(purge): adding purge command

devservices/commands/status.py
=> feat(status): Include container name

devservices/commands/status.py
=> ref(status): Improving status command when service isn't running

README.md
This adds update and purge to readme
=> chore(readme): Add update and purge to README

README.md, scripts/bump-version.sh
Recommended way of installation should be through virtualenv
=> feat(readme): Update installation instructions

devservices/main.py
Adds the current user via Sentry to better understand the impact of issues.
=> feat(sentry): Adding user to sentry

devservices/utils/dependencies.py
=> chore(debug): Add cwd for debug logs for dependencies

README.md, devservices/commands/down.py, devservices/commands/up.py, devservices/main.py, tests/commands/test_down.py, tests/commands/test_up.py
Renaming start and stop to up and down by popular demand.
=> ref(start/stop): Renaming start and stop to up and down

devservices/commands/status.py
Fixing the doc-string for the status command.
=> fix(status): Fixing doc-string

tests/utils/test_dependencies.py
This adds some missing tests to support modes for `install_and_verify_dependencies`
=> feat(testing): Add tests for `install_and_verify_dependencies` for modes

devservices/commands/up.py, tests/commands/test_up.py
We will start using external network for devservices
=> feat(network): Create devservices network if it doesn't exist

tests/commands/test_status.py
This adds tests for status command
=> feat(tests): Test status command

devservices/commands/list_dependencies.py, tests/commands/test_list_dependencies.py
This adds testing for listing dependencies of a service
=> feat(testing): Test list dependencies

devservices/commands/list_services.py, tests/commands/test_list_services.py
This change adds mode service is running in to the ls command
=> feat(list-dependencies): list-dependencies shows mode of service that is running

devservices/utils/dependencies.py, tests/utils/test_dependencies.py
We've had some intermittent issues with git fetch that are difficult to debug with the current context we have in Sentry. This change aims to improve the context we give to Sentry by including some of the git config to help us better debug future issues with git fetch.
=> ref(dependencies): Adding more context to sentry

devservices/utils/docker.py, tests/utils/test_docker.py
Noticed this low hanging fruit when reviewing the code.
=> chore(docker): Cleaning up docker utils

devservices/commands/up.py, devservices/configs/service_config.py, devservices/utils/docker.py, devservices/utils/file_lock.py
Fixing various linter issues and removing old comments
=> chore: cleaning up various nits

devservices/utils/services.py, tests/utils/test_services.py
https://getsentry.atlassian.net/browse/DEVINFRA-572
=> ref(commands): Improving error message for service not found DEVINFRA-572

devservices/utils/dependencies.py
Fixes: https://getsentry.atlassian.net/browse/DEVINFRA-580
Adds retries to fetch to help mitigate transient issues with fetching certain repos. We should dig deeper into what causes these transient issues in the future, but this should help in the meantime since these issues seem to self-correct.
=> fix(dependencies): Adding retries to fetch

devservices/utils/console.py
This skips the animated loader for CI
=> chore(ci): Skip loader for CI

devservices/commands/down.py, devservices/commands/logs.py, devservices/commands/status.py, devservices/commands/up.py, devservices/utils/docker_compose.py, tests/commands/test_logs.py, tests/commands/test_up.py, tests/utils/test_docker_compose.py
Moving it back for the time being since we didn't end up needing to change it at this time to make the changes we made in #201.
=> chore: Moving get_docker_compose_commands_to_run back

tests/commands/test_up.py
The main goal of this PR is to move away from mocking the `devservices.utils.docker_compose.subprocess.run` in favor of mocking `devservices.commands.up.run_cmd` instead as that gives us more control and avoids over-mocking that can come back to bite us in the future.
=> chore(up): Cleaning up tests

devservices/exceptions.py
example: https://sentry.sentry.io/issues/6187390843/?project=4507946704961536&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=7d&stream_index=0
=> feat(devservices): Use more specific error message for docker compose error exception

tests/commands/test_down.py
Similar to the recent changes I made in the up tests (#205)
=> chore(down): Cleaning up down tests

devservices/commands/down.py, devservices/commands/logs.py, devservices/commands/status.py, devservices/commands/up.py, devservices/exceptions.py, devservices/utils/dependencies.py
Improving error messaging and observability of dependency errors by tracking stderr higher up and providing users with a suggestion when dependency errors occur.
https://getsentry.atlassian.net/browse/DEVINFRA-598
=> ref(dependencies): Improving error messages for dependency errors

devservices/main.py
Making this environment variable more specific for clarity when used in CI workflow files.
=> chore(devservices): Make env variable name more specific 

devservices/main.py
Adding proper sentry release that tracks the devservices version
=> chore(sentry): Adding sentry release

devservices/exceptions.py, devservices/main.py, devservices/utils/git.py, tests/utils/test_git.py
Adding context about the user's machine and the user's git version to Sentry.
=> ref(sentry): adding more context to sentry

.github/workflows/build.yml
https://github.com/actions/cache/discussions/1510
=> fix(gha): Updating actions/cache to 4.2.0

devservices/main.py
This adds a lot of context for devservices transactions in CI
https://getsentry.atlassian.net/browse/DEVINFRA-643
=> feat(ci): Add tags for ci runs

tests/utils/test_dependencies.py
=> fix(tests): Fixing test variable naming

devservices/commands/up.py, tests/commands/test_up.py
https://github.com/user-attachments/assets/7bc19aa7-084b-4d07-b4cb-79df1bc1f8c6
=> feat(up): Add better UX when pulling images

devservices/exceptions.py, devservices/utils/supervisor.py, requirements.txt, tests/utils/test_supervisor.py
This adds a supervisor manager class to manage all things supervisor
=> feat(supervisor): Add initial supervisor logic

tests/utils/test_supervisor.py
https://linear.app/getsentry/issue/DI-686/add-some-tests-for-socket-connections-for-supervisor
=> chore(supervisor): Add some socket tests

README.md
Adding information about toggle to the readme.
=> chore(toggle): Add documentation for toggle

devservices/commands/toggle.py, tests/commands/test_toggle.py
Fixing a bug with enums that I missed in the previous PR
=> fix(toggle): Fixing toggle enums again
