getsentry/devservices

setup.cfg, src/commands/list_dependencies.py, src/configs/service_config.py, src/utils/devenv.py
* Renamed devservices config to service config to be clearer.
* Moved the service config to a new configs directory to improve organization.
* Added mypy ignore for pyyaml nonsense (https://github.com/python/mypy/issues/10632).
* Renamed code_root to coderoot.
=> ref(config): Renaming service config and moving it to a config dir

.pre-commit-config.yaml, requirements.txt, setup.py, src/configs/service_config.py
This removes pydantic in favor of [dataclasses](https://docs.python.org/3/library/dataclasses.html)
Reasons why:
- Pydantic is known to be slow
- we don't need the benefits Pydantic gives for complex data models
- one less dependency
=> Remove pydantic

src/commands/list_dependencies.py, src/commands/list_services.py, src/configs/service_config.py, src/main.py, src/services.py
Doing some general work to improve how we get information about available services to run:
* Adding list-services command
* Adding new logic for determining which services are available locally
=> feat(services): Adding list-services command

src/commands/list_dependencies.py, src/configs/service_config.py, src/services.py
Removing circular dependency by refactoring how we handle loading the config, simplifying the logic in the process. Now instead of passing an optional service into load_service_config, we pass nothing, but only if a service name is not provided (meaning the user is running the command from a repo directly).
=> chore(service-config): Refactoring service config loading

src/configs/service_config.py, src/utils/services.py
Importing list, dict, ect from typing is no longer required in recent versions of python.
=> chore(typing): Switching to modern typing practices

src/commands/status.py
Rather than printing an empty status, this change informs the user that the service is not running. I can't think of any cases where the `status_json` would be empty when the service is running, but if there are any, let me know.
=> fix(cli): Added status when service isn't running

src/configs/service_config.py, tests/configs/test_service_config.py
* Splitting up try excepts to limit the amount of code in the try statements as it is a [best practice](https://peps.python.org/pep-0008/#:~:text=Additionally%2C%20for%20all%20try/except%20clauses%2C%20limit%20the%20try%20clause%20to%20the%20absolute%20minimum%20amount%20of%20code%20necessary.%20Again%2C%20this%20avoids%20masking%20bugs%3A)
* Removing redundant error handling
* Adding more error handling where necessary for type errors related to dependencies
* Adding some general validation to catch more issues with service configs
* Improving test coverage
=> ref(config): Adding more validation and tests for service config

requirements.txt, src/main.py
=> feat(devservices): Add sentry to devservices

src/main.py
Removes the "Sentry is attempting to send 2 pending events" messages.
=> fix(cli): Adding atexit handler to avoid sending sentry logs to console

src/commands/start.py, src/commands/stop.py, src/utils/console.py, src/utils/terminal.py
Adding a basic status loader utility to make the CLI more user friendly. This utility spins as long-running commands process to show the user that work is being down behind the scenes, improving UX.
=> Adding status loader utility

README.md
Adds some basic info to the readme
=> feat(docs): Add readme

devservices/configs/service_config.py, tests/configs/test_service_config.py
In preparation for the dependency management, I am adding some more fields to better track remote dependencies. Additionally, keeping them in a separate dataclass enables us to ensure they are mutually inclusive.
=> ref(service-config): Updating service config to include remote deps

.craft.yml, .github/workflows/build.yml, devservices/main.py, pyoxidizer.bzl, pyproject.toml, requirements-dev.txt
This PR helps us publish a binary for devservices, aiding in a system wide installation of the cli tool. We're using PyOxidizer, which packages the python interpreter into the binary. 
1. builds a binary using PyOxidizer for linux and macos
2. uploads artifacts for the craft release job
=> feat(release): Build and upload binary

README.md, scripts/bump-version.sh
adds some details for installation
=> feat(readme): Add installation details

devservices/commands/logs.py, devservices/commands/start.py, devservices/commands/status.py, devservices/commands/stop.py, tests/commands/test_start.py, tests/commands/test_stop.py
This makes it much easier for us to determine how many docker compose configs are currently in use
`docker compose ls` after starting relay and snuba
closes https://github.com/getsentry/devservices/issues/45
Before:
```
NAME                STATUS              CONFIG FILES
devservices         running(3)          /Users/hubertdeng/code/relay/devservices/config.yml,/Users/hubertdeng/code/snuba/devservices/config.yml
```
After:
```
NAME                STATUS              CONFIG FILES
relay               running(2)          /Users/hubertdeng/code/relay/devservices/config.yml
snuba               running(3)          /Users/hubertdeng/code/snuba/devservices/config.yml
```
=> chore(start): Specify project name when starting services

devservices/commands/logs.py, devservices/commands/start.py, devservices/commands/status.py, devservices/commands/stop.py, devservices/utils/docker_compose.py
Found a way to abstract away a bunch of duplicate code by letting the `run_docker_compose_command` utility to automatically add `-p` and `-f` using the service info.
=> ref(docker-compose): refactoring docker compose util

devservices/exceptions.py, devservices/utils/dependencies.py, tests/utils/test_dependencies.py
Added logic to handle more edge cases and corresponding tests.
* Rather than just checking if the working copy exists, check if it is a valid repo
* When updating a dependency, do so forcibly
* When checking out a dependency, clear any existing files that may exist (this probably will never happen, but it's worth being extra safe)
=> ref(dep): Addressing dependency edge cases

devservices/utils/docker_compose.py, tests/commands/test_start.py, tests/commands/test_stop.py
=> feat(docker-compose): Simplify docker compose environment injection

devservices/constants.py, devservices/exceptions.py, devservices/utils/dependencies.py, tests/utils/test_dependencies.py
=> ref(dependencies): Adding git proper git config management for deps

devservices/constants.py, devservices/exceptions.py, devservices/utils/docker_compose.py, tests/utils/test_docker_compose.py
This pins docker compose as a user plugin for docker for version 2.29.7 for our users. That way, we have full control over docker compose behavior
=> ref: Pin docker compose version for users

devservices/utils/services.py
This enables us to alert users to issues with configs for repos they have cloned locally.
=> ref(services): Add message when service is found with invalid config

devservices/commands/check_for_update.py, devservices/commands/update.py, devservices/constants.py, devservices/exceptions.py, devservices/main.py, devservices/utils/docker_compose.py, devservices/utils/install_binary.py, requirements.txt, tests/commands/test_update.py, tests/utils/test_docker_compose.py, tests/utils/test_download_and_install_binary.py, tests/utils/test_install_binary.py
This adds the update command to devservices
For global installs, this will download the latest binary off of GitHub, detect the correct binary for linux/darwin operating systems, and automatically install. It will also automatically check for update after each invocation of devservices.
For installs in virtual environments, it prints instructions to update the requirements.txt.
=> feat(commands): Add update command

devservices/utils/docker_compose.py
Closes https://github.com/getsentry/devservices/issues/80
=> fix(docker-compose): Ensure user plugin directory is created before proceeding with install

devservices/utils/dependencies.py, devservices/utils/docker_compose.py, tests/utils/test_dependencies.py
To enable us to properly manage start and stop (as well as other commands) with nested dependencies, we need to know what nested service dependencies we need to start/stop separately and what dependencies may be shared between services.
=> ref(dependencies): Providing information about installed remote dependencies after installing

devservices/commands/logs.py, devservices/commands/start.py, devservices/commands/status.py, devservices/commands/stop.py, devservices/configs/service_config.py, devservices/utils/dependencies.py, devservices/utils/docker_compose.py, testing/resources/child-service-repo/README.md, testing/resources/child-service-repo/devservices/config.yml, testing/resources/grandparent-service-repo/README.md, testing/resources/grandparent-service-repo/devservices/config.yml, testing/resources/parent-service-repo/README.md, testing/resources/parent-service-repo/devservices/config.yml, tests/commands/test_start.py, tests/commands/test_stop.py, tests/configs/test_service_config.py, tests/utils/test_docker_compose.py
This adds support for running docker commands for nested remote dependencies. Each docker compose command is run  with its own appropriate service name as its project.  
For example:
```
Grandparent (grandparent-service)
--> Parent (parent-service)
----> Child (child-service-1, child-service-2)
```
Docker Compose projects:
Grandparent: 
- grandparent-service
Parent:
- parent-service
Child:
- child-service-1
- child-service-2
=> feat(devservices): Run commands for nested dependencies by project

devservices/commands/logs.py
Fixing naming in the logs command to avoid overwriting the function definition itself
=> fix(logs): Fixing naming issue with logs

devservices/commands/logs.py, devservices/commands/start.py, devservices/commands/status.py, devservices/commands/stop.py, devservices/exceptions.py, devservices/utils/dependencies.py
=> chore(errors): Improving the error msgs for dependency errors

devservices/exceptions.py, devservices/main.py, devservices/utils/docker.py, devservices/utils/docker_compose.py, tests/utils/test_docker_compose.py
=> chore(errors): Adding graceful handling when docker daemon isn't running

devservices/commands/list_services.py, devservices/utils/docker_compose.py, tests/commands/test_list_services.py
For `list-services`, we are incorrectly marking local services as running when services are brought up with remote dependencies. 
Say for example snuba is brought up that depends on shared-redis and shared-kafka whose definitions are pulled in remotely. `devservices list-services` would show local copies of shared-redis and shared-kafka as running. This fixes that
=> fix(list-services): Use state for finding status of list services

devservices/commands/logs.py, devservices/constants.py
This limits the amount of logs that are printed to console. It also fixes a bug where logs can be printed despite a service is not running if a dependency of the service is running.
=> fix(logs): Limit log length and check to ensure service is running before printing logs

devservices/commands/list_dependencies.py, devservices/commands/list_services.py, devservices/commands/logs.py, devservices/commands/purge.py, devservices/commands/start.py, devservices/commands/status.py, devservices/commands/stop.py, devservices/commands/update.py, devservices/main.py, devservices/utils/console.py, devservices/utils/docker_compose.py, devservices/utils/install_binary.py, devservices/utils/services.py, tests/commands/test_list_services.py, tests/commands/test_update.py
Fixes #116. Adds a utility for printing color the the console in a relatively easy and standardized way.
=> ref(logs): Updating logs to use console util

devservices/commands/logs.py, devservices/commands/start.py, devservices/commands/status.py, devservices/commands/stop.py, devservices/utils/dependencies.py, devservices/utils/docker_compose.py, tests/commands/test_start.py
Starting to reduce the complexity of the run_docker_compose_command by decoupling dependency installation logic.
=> ref(docker-compose): Moving dependency logic out of docker compose

devservices/commands/start.py, devservices/commands/stop.py, devservices/constants.py, devservices/main.py, devservices/utils/dependencies.py, devservices/utils/docker_compose.py, tests/commands/test_start.py, tests/commands/test_stop.py
This adds additional logs for commands run during start/stop
=> feat(debug): Add debug mode for start and stop

devservices/commands/purge.py, devservices/exceptions.py, devservices/utils/console.py, devservices/utils/docker.py, devservices/utils/state.py, tests/commands/test_purge.py, tests/utils/test_docker.py
Fixes #62 (mostly). We could still add a means of clearing all docker volumes as well, but that can come later.
=> feat(purge): Adding state clear functionality to purge

devservices/utils/dependencies.py
Fixes #122. Removing the use of clear since it doesn't exist and isn't actually required. Since we set the values for sparse checkout rather than add them, we shouldn't need to clear them in between.
=> fix(dependencies): Removing sparse-checkout clear command

devservices/main.py
There was an issue with the namespace, causing certain commands without a debug flag to error out. This changes resolves the issue by making sure the debug flag is in the args beforehand.
=> fix(debug): Fixing debug flag

devservices/commands/logs.py, tests/commands/test_logs.py
Fixes a bug where running the logs command without a specified service always fails. Added tests to hopefully catch bugs like this in the future and prevent regressions. Fixes #136
=> fix(logs): Fixing bug in logs command, adding tests

devservices/commands/list_dependencies.py, devservices/commands/logs.py, devservices/commands/start.py, devservices/commands/status.py, devservices/commands/stop.py, devservices/main.py
Currently, our error handling takes care of most cases, but we still want to be alerting of these issues in Sentry.
=> feat(sentry): Adding explicit capture for exceptions

devservices/commands/check_for_update.py, devservices/commands/update.py, devservices/main.py
Tracking the devservices version via Sentry for better observability. Additionally, I removed some unnecessary code and cleaned up our usage of sentry to import only what we need.
=> feat(sentry): Adding version tag, cleaning up version logic

devservices/commands/start.py, devservices/utils/docker_compose.py, tests/commands/test_start.py
This adds multithreading for docker compose commands and waits for containers to pass healthchecks before exiting
=> feat(start): Add threading and condition to wait for containers to be healthy

devservices/commands/logs.py, devservices/commands/start.py, devservices/commands/status.py, devservices/commands/stop.py, devservices/utils/docker_compose.py, tests/commands/test_logs.py, tests/commands/test_start.py, tests/commands/test_stop.py, tests/utils/test_docker_compose.py
Fixes https://github.com/getsentry/devservices/issues/109. While it seemed nice to abstract out a lot of the logic initially, it has made command specific logic difficult to deal with, slowing down development. While this change looks like a step backward, it should improve development going forward as we are no longer bound by a function that does way too much.
=> ref(docker-compose): De-abstracting run_docker_compose_command

devservices/commands/purge.py, devservices/constants.py, tests/commands/test_purge.py
We hit some issues with race conditions and multiple instances of the same docker network being created. While we are going to fix that issue separately, we should also be able to clear the docker networks as a backup.
=> ref(purge): removing docker networks with purge

devservices/exceptions.py, devservices/utils/dependencies.py
Currently, our dependency logic installs and returns all dependencies rather than just those needed for a specific mode. This PR changes that to be more efficient and accurate.
=> ref(dependencies): Updating dependency management to handle modes

tests/commands/test_purge.py
Not sure how this slipped by, but I am pretty sure this was destined to fail once run with devservices running in the background since it would try to remove the network.
=> fix(purge): Fixing purge test

devservices/commands/down.py, devservices/commands/up.py, tests/commands/test_down.py, tests/commands/test_up.py, tests/utils/test_dependencies.py
This PR adds support for modes for `devservices up` and `devservices down`.
The mode will be passed in as an option --mode
`devservices start sentry --mode migrations`
When running `devservices down` on a service, the mode will automatically be detected to bring a service down. If for some reason state is corrupted, devservices will try to bring down all the dependencies defined in the `default` mode.
=> feat(devservices): Support modes for up/down

devservices/commands/down.py, devservices/commands/list_dependencies.py, devservices/commands/logs.py, devservices/commands/status.py, devservices/commands/up.py
Currently, we have very broad error handling for finding matching services in most commands. This change updates the error  handling to be more specific and targeted.
=> ref(commands): Cleaning up error handling for commands

devservices/commands/purge.py, devservices/commands/update.py
Prefixing unused args with an underscore to make my linter happy.
=> fix(commands): Cleaning up unused args

devservices/utils/docker_compose.py, tests/utils/test_docker_compose.py
This is temporary before we construct a dependency graph to accurately start services in order
=> feat(devservices): Start shared services first

devservices/commands/up.py
Fixes: `ValueError: stdout and stderr arguments may not be used with capture_output.`
=> fix(up): Remove capture output flag when creating devservices network

devservices/commands/down.py, devservices/commands/logs.py, devservices/commands/status.py, devservices/commands/up.py, devservices/utils/dependencies.py, devservices/utils/docker_compose.py, tests/utils/test_dependencies.py, tests/utils/test_docker_compose.py
Currently, our logic does not handle bringing up services in the correct order such that dependencies are started before their dependents. This change addresses that by constructing a dependency graph and using reverse topological ordering to determine the ordering in which we should bring services up.
=> feat(dependency): Adding dependency graph to start services

tests/utils/test_services.py
Adding first test for services utility. Tests that local repos with invalid devservices configs are skipped but a warning is logged for the user.
=> feat(services): Adding test for local services with invalid config

testing/resources/non-devservices-repo/README.md, tests/utils/test_services.py
Adding an additional test to cover the case where we skip over local repos when they don't contain a devservices config.
=> feat(services): Adding test for skipping non-devservices repos

devservices/commands/down.py, devservices/commands/list_dependencies.py, devservices/commands/logs.py, devservices/commands/status.py, devservices/commands/up.py, tests/commands/test_down.py, tests/commands/test_logs.py, tests/commands/test_up.py
This adds additional noise, so let's not report to sentry if ServiceNotFound error is raised
=> fix(sentry): Do not report to sentry if service is not found

devservices/commands/up.py, devservices/utils/dependencies.py, tests/utils/test_dependencies.py
Fixing the dependency graph creation when a mode doesn't contain all of the dependencies and not all dependencies are downloaded. This bug happened because when we made the dependency graph we would traverse all dependencies, even the ones not included in the specified mode, meaning we would potentially traverse some that aren't installed leading to errors. This change addresses that issue by only traversing relevant dependencies for the given mode.
=> fix(dependencies): Fixing dependency graph construction for simple modes

devservices/utils/devenv.py
using ~/code doesn't work, so this fixes it
=> fix(coderoot): Use expanduser

devservices/utils/dependencies.py, tests/utils/test_dependencies.py
This change updates our installation logic to only install dependencies necessary for a given mode even for nested dependencies which should help install be more efficient.
=> fix(dependencies): Only install dependenices needed for the mode

devservices/commands/purge.py, devservices/constants.py, devservices/exceptions.py, devservices/utils/docker.py, tests/commands/test_purge.py, tests/utils/test_docker.py
Updating purge to stop relevant containers and remove them rather than stopping all containers. This makes use of the newly added labels we added to the configs of the various services.
=> feat(purge): Updating purge to only stop relevant containers

devservices/main.py
We are getting rate limited occasionally, which can fail CI jobs.
https://github.com/getsentry/sentry/actions/runs/12265809503/job/34222670505?pr=81941
=> fix(CI): Avoid checking for update in CI

devservices/commands/down.py
Currently we don't handle exceptions for `get_non_shared_remote_dependencies`, which this change aims to address.
=> fix(down): Adding error handling to get_non_shared_remote_dependencies

devservices/commands/purge.py, devservices/utils/docker.py, tests/commands/test_purge.py, tests/utils/test_docker.py
Adding functionality to remove volumes used by active devservices containers during the purge command. This aims to make purge more effective at clearing all state. One edge case that will still exist that this logic doesn't account for is clearing volumes for containers that are no longer up.
=> feat(purge): Purge removes corresponding volumes

devservices/commands/up.py, tests/commands/test_up.py
Currently, we do not explicitly pull new images when bringing up containers. This change aims to fix that by setting the `pull policy` to `always`.
=> fix(up): Always pull new images

devservices/commands/purge.py, devservices/utils/docker.py, tests/commands/test_purge.py, tests/utils/test_docker.py
Improving error handling of purge and improving efficiency of the network removal logic.
=> ref(purge): Cleaning up purge network logic

devservices/commands/purge.py, devservices/utils/docker.py, tests/commands/test_purge.py, tests/utils/test_docker.py
Currently, we only stop/remove running devservices containers during purge which means there is an edge case where problematic containers are not running and thus are not removed by purge. This can lead to issues such as "network not found" errors when starting up.
https://getsentry.atlassian.net/browse/DEVINFRA-565
=> fix(purge): Updating purge to stop/remove all devservices containers

devservices/main.py
This message can be confusing, especially since in virtual environments this is not actionable for people.
=> chore(devservices): Remove update warning message

pyproject.toml
This should resolve errors if packaging/sentry_sdk is not installed by default
=> fix: Add missing dependencies to pyproject.toml

devservices/commands/status.py, tests/commands/test_status.py
Currently, the status command doesn't have consistent ordering across runs. This change updates it so that the output is sorted by the respective service names.
https://getsentry.atlassian.net/browse/DEVINFRA-566
=> fix(status): Adding consistent ordering to status output

devservices/commands/down.py, devservices/commands/list_dependencies.py, devservices/commands/logs.py, devservices/commands/status.py, devservices/commands/up.py, devservices/configs/service_config.py, tests/commands/test_down.py, tests/commands/test_list_dependencies.py, tests/commands/test_logs.py, tests/commands/test_status.py, tests/commands/test_up.py, tests/configs/test_service_config.py
https://getsentry.atlassian.net/browse/DEVINFRA-572
=> ref(commands): Improving error messages

tests/commands/test_up.py
Adding some usage of the mock_subprocess_check_output to improve testing and avoid unused args.
=> chore(up): cleaning up tests

devservices/commands/down.py, devservices/utils/dependencies.py, tests/commands/test_down.py
Fixes: https://getsentry.atlassian.net/browse/DEVINFRA-570 and https://getsentry.atlassian.net/browse/DEVINFRA-582.
Adds logic to properly handle bringing services down in specific edge cases that were previously not supported. This includes bringing down a service that is being used by another, which should not bring anything down. Additionally, it supports bringing down base services such as redis which are considered remote to other services but local to themselves. Additionally, this adds proper testing so we shouldn't have regressions going forward.
It is worth noting that this doesn't support what I would consider 'ideal' behavior when it comes to modes. It takes the conservative approach and doesn't bring things down unnecessarily, but doesn't stop certain dependencies based on the …
=> fix(down): Fixing down's logic and adding proper tests

devservices/utils/dependencies.py, devservices/utils/docker_compose.py
https://stackoverflow.com/questions/34619790/pylint-message-logging-format-interpolation
=> fix(logger): Update logger to no longer use fstrings

devservices/utils/dependencies.py
Currently, we log this an exception when it isn't particularly actionable for users. While we don't need to show users about the retries, we still want to keep an eye on them to get a better idea of how often this issue occurs hence the use of capture_message.
=> ref(dependencies): Switching to debug logs and sentry messages

devservices/commands/down.py, devservices/commands/list_services.py, devservices/commands/logs.py, devservices/commands/up.py, devservices/utils/dependencies.py, devservices/utils/state.py, tests/commands/test_down.py, tests/commands/test_list_services.py, tests/commands/test_logs.py, tests/commands/test_purge.py, tests/commands/test_up.py, tests/utils/test_dependencies.py, tests/utils/test_state.py
This will allow us to support a `starting_services` table, allowing us to clean up intermediate states users may get into if `devservices up` fails. Then, `devservices down` will clean things up
=> chore(state): Refactor state to support starting services table

devservices/commands/down.py, devservices/commands/up.py, devservices/utils/dependencies.py, tests/commands/test_down.py, tests/commands/test_up.py
Currently, you can only bring down services that have been completely brought up. This is not ideal as it makes it difficult to bring down services that are partially up, forcing users to use the purge command. This change improves down so that you can bring down services once they start being brought up even if they are not fully up.
https://getsentry.atlassian.net/browse/DEVINFRA-455
=> fix(down): Enable bringing down starting services

devservices/commands/list_services.py, devservices/commands/logs.py, tests/commands/test_list_services.py, tests/commands/test_logs.py
https://getsentry.atlassian.net/browse/DEVINFRA-596 Now that we track both starting and started services, commands such as `logs` and `list-services` should be able to work with starting services. This change updates those commands to do just that by treating both starting and started services as not-stopped (aka running).
=> ref(commands): Improving commands to use starting services and started

devservices/exceptions.py, devservices/utils/dependencies.py, tests/commands/test_up.py
https://getsentry.atlassian.net/browse/DEVINFRA-594. Currently, there is no good way of seeing modes available to be run, and mistyping a mode doesn't give you any indication of possible options. This change fixes that by including available modes in the error message.
=> ref(up): Show available modes

devservices/utils/dependencies.py, tests/utils/test_dependencies.py
https://getsentry.atlassian.net/browse/DEVINFRA-598. Adding additional error handling to the core dependency logic. Fixed the `_run_command` function to now properly propagate the stderr which it did not do previously which should now give us more information into the failures we see. For now I opted not to add retries to anything besides fetch since fetch is by far the most likely to face transient errors, and retrying certain other commands can put us in a potentially problematic state.
More improvements to the core dependency logic, specifically around the git config are coming in another PR.
=> ref(dependencies): Improving error handling for dependency logic

devservices/constants.py, tests/commands/test_up.py
snuba healthcheck [here](https://github.com/getsentry/sentry/blob/7147e8e444c1319ad908d3a761eebcf2c3849604/src/sentry/runner/commands/devservices.py#L869) is 120 seconds, people are complaining about timeouts being exceeded so let's bump this
=> chore(healthchecks): Bump healthcheck timeout to 2 minutes

devservices/utils/dependencies.py, tests/utils/test_dependencies.py
https://getsentry.atlassian.net/browse/DEVINFRA-607
One of the most common sources of fetch failures is submodules, which we do not care about in the context of our dependency management. To mitigate these issues, we can just not recurse submodules all together when fetching.
=> fix(dependencies): Exclude submodules from fetch

devservices/main.py
Fixes a bug with the `DEVSERVICES_DISABLE_SENTRY` env var not being handled correctly.
=> fix(sentry): Fixing disable sentry env var logic

devservices/utils/docker_compose.py, tests/utils/test_docker_compose.py
If `docker compose version --short` fails, exception is not thrown. This fixes that
=> fix(docker-compose): Allow docker compose verification logic to properly throw

devservices/main.py
Making this a string instead of a boolean specifically so that runners can report to Sentry under the ci environment
=> ref(sentry): Tweak devservices environment env variable

devservices/commands/update.py
A quick fix that updates the "update" command's help message to start with a capital letter to follow the same pattern as the rest.
=> chore(devservices): Fixing capitalization in update help message

devservices/utils/dependencies.py, tests/utils/test_dependencies.py
https://getsentry.atlassian.net/browse/DEVINFRA-609
Currently the logic used in non_shared_remote_dependencies dependencies will get all dependencies of the service(s) not being stopped, which becomes problematic when we then check if the dependencies are installed correctly which if they aren't part of the running modes, they won't be. The change made in this PR updates the logic to only consider dependencies of the running modes.
=> fix(dependencies): Only get dependencies that should be running

devservices/commands/down.py
Currently, when running down when the service is not currently up, it is marked as an internal_error by Sentry despite exiting with a zero status code. To fix this, I updated the logic to return instead.
=> chore(sentry): Fixing status for down when not running

devservices/main.py
This should prevent confusion between the current `platform` field.
=> chore(sentry): updating platform tag name

devservices/utils/docker_compose.py, tests/utils/test_docker_compose.py
This cleans things up a bit and allows us to reuse some logic
=> chore(docker-compose): Move `docker compose version` command to separate function

devservices/commands/down.py, devservices/commands/list_dependencies.py, devservices/commands/logs.py, devservices/commands/up.py, devservices/main.py
For transactions that do not have a trace that is tied to an error that has a higher level than "info", we manually set the status to unknown
=> feat(sentry): Manually set status of transactions

README.md
This adds a lot more description for folks on how to setup a devservices config
=> feat(readme): Add config section to readme

devservices/utils/state.py, tests/utils/test_state.py
https://getsentry.atlassian.net/browse/DEVINFRA-627
Adding the state that will be used to track the runtime of services (either local or containerized). This is to enable more comprehensive cross-repo local development capabilities.
=> feat(runtime): Adding state to track runtime

devservices/commands/down.py, devservices/utils/dependencies.py, tests/commands/test_down.py
Updating the down command to work with services set to use a local runtime. Ensures down doesn't bring down services that are set to run locally when bringing down a dependent service.
https://getsentry.atlassian.net/browse/DEVINFRA-637
=> ref(down): Updating down to work with local runtime

devservices/commands/up.py, devservices/utils/docker_compose.py, tests/utils/test_docker_compose.py
https://linear.app/getsentry/issue/DI-660/healthcheck-bug-for-when-additional-containers-are-already-up
=> fix(devservices):  Fix healthcheck bug

devservices/commands/up.py, tests/commands/test_up.py
Adds visibility into why certain dependencies are skipped if they have a local runtime when running the up command.
https://linear.app/getsentry/issue/DI-605/improve-visibility-of-service-runtimes-for-users
=> ref(up): Add info about local runtime in up

devservices/commands/status.py, devservices/constants.py, devservices/utils/console.py, tests/commands/test_status.py
Revamping the status command to properly visualize the hierarchy of services and their dependencies. This includes showing which services are set to run locally (via local runtime) or are containerized (brought up by devservices automatically). With this updated logic also comes more comprehensive testing via smaller functional components.
https://linear.app/getsentry/issue/DI-647/rework-status-command
Before:
After:
Note: The new version may look more repetitive because redis and kafka appear multiple times, but that is intentional since they are used by both relay and snuba.
=> ref(status): Revamp status command

devservices/commands/up.py, tests/commands/test_up.py
https://linear.app/getsentry/issue/DI-684/only-show-skipped-dependencies-once-when-running-up
=> fix(up): Only show skipped message once

devservices/constants.py, devservices/utils/supervisor.py, tests/utils/test_supervisor.py
This is important because it abstracts config settings that are not relevant away from the end user and makes it easier to handle clashing that can happen between connections with ports.
This opens socket connections through sock files that are named after the devservices services. This prevents clashing ports entirely
=> feat(supervisor): Generate supervisor config file to local dir

devservices/utils/supervisor.py, tests/utils/test_supervisor.py
Initially this was the fg command, but changed this since foregrounding a process is not reliable. 
https://linear.app/getsentry/issue/DI-663/support-retrieving-logs-of-supervisor-processes
=> feat(supervisor): Add tailing logs function

devservices/constants.py, tests/utils/test_docker_compose.py
https://linear.app/getsentry/issue/DI-741/ci-failure-docker-compose-download-failure
I've copied the appropriate binaries over to our bucket.
=> feat: vendor docker-compose binaries

devservices/commands/toggle.py, tests/commands/test_toggle.py
Fixing a small issue with formatting enums
=> fix(toggle): Fixing toggle formatting with enums

devservices/commands/serve.py, devservices/constants.py, devservices/main.py, devservices/utils/supervisor.py, testing/utils.py, tests/commands/test_serve.py, tests/utils/test_supervisor.py
This adds the initial serve command to devservices. It will parse the supervisor config file for the program devserver and run that in interactive mode in terminal
https://linear.app/getsentry/issue/DI-651/add-devservices-serve-command
=> feat(serve): Add initial serve command

devservices/utils/supervisor.py, tests/utils/test_supervisor.py
program is the definition of how to run something
process is an instance
This tries to align more with the terminology
=> chore(terminology): Be more distinct between program vs process

devservices/commands/down.py, devservices/commands/toggle.py, devservices/commands/up.py, devservices/utils/dependencies.py, tests/commands/test_down.py, tests/commands/test_toggle.py, tests/commands/test_up.py, tests/utils/test_dependencies.py
This was feedback we got from early users. In most cases, it makes sense for devservices to automatically bring up and down services local dependencies when bringing up/down dependent services. This is the default case now, and if the user wants to bring up/down a local runtime dependency in a non-default mode, they can use the --exclude-local.
=> ref(toggle): Auto bring up/down local runtimes services

.github/workflows/test.yml, pyproject.toml, requirements.txt
sentry internal pypi supports python 3.11+ now, so bumping this
Also updates some other packages
=> chore(versioning): Bumping min python version to 3.11

devservices/commands/up.py, tests/commands/test_up.py
Currently, `devservices up` will always print out `Starting dependencies with local runtimes...` (unless the user passes in the exclude_local flag), even if there are no dependencies with local runtimes. This was a quick and easy fix, and while I was in the area, I added some tests to ensure we validate when this message is printed as well cleaned up the surrounding logic.
=> fix(up): Cleaning up 'up' local runtime logic

devservices/commands/toggle.py, tests/commands/test_toggle.py
Updating toggling active dependencies to be consistent with the behavior of bringing up a service with dependencies with local runtimes. When toggling a containerized dependency that is active, it should be brought down and brought back up again locally, similar to how the up command works.
=> feat(toggle): Updating toggling active dependency to be consistent

devservices/commands/up.py, devservices/utils/docker_compose.py, tests/commands/test_up.py
https://linear.app/getsentry/issue/DI-739/ci-failure-ghrc-image-download-tls-handshake-error
ghcr.io sometimes flakes but they're generally blips that can be retried
there's no docker compose pull retries so we have to do it ourselves
i added it to run_cmd in case we want to easily wrap other run_cmds in the future
=> feat: exponentially retry pulling

devservices/commands/list_services.py, devservices/configs/service_config.py, devservices/utils/services.py, tests/commands/test_list_services.py, tests/configs/test_service_config.py, tests/utils/test_services.py
This adds safeguards to ensure that non-remote dependencies must have a docker compose service associated with them. It also fixes a bug where config validation fails, but the error is not raised properly
part of https://linear.app/getsentry/issue/DI-762/config-validation-for-dependencies
=> feat(config): Add validation for non remote dependencies

devservices/commands/up.py, tests/commands/test_up.py
Fixes a bug that causes dependencies with local runtimes to use the same mode as the dependent service is being brought up with instead of default. Updated our tests to make sure we properly cover this going forward. Left a TODO that I will make an issue for in linear as well.
=> fix(up): Fixing local runtime dependency mode

devservices/commands/up.py
Adding more context via spans and Sentry context. This will enable us to better track the performance of specific parts of the up command as well as better understand usage of the toggle command by tracking what dependencies are set to local runtimes when using up.
I broke off `_install_service_dependencies` as I felt it was more readable that way, especially since it would have been setting a variable in an even more nested context which would be easy to miss. I opted not to break more things off in the interest of keeping this PR on track.
I did my best to add as much context as seemed reasonable without overdoing it. If I missed anything crucial or added unnecessary context, let me know.
=> ref(up): Adding more context to up

devservices/utils/supervisor.py, tests/utils/test_supervisor.py
This change makes it so that config changes are picked up on `devservices up` invocations. Edited or new programs will not be automatically be brought up. This means that if a config change goes in for a program that is currently running, the mode with the program must be brought up again. This behavior seems fine for now, and we can add on functionality later on to ensure the same programs running before are brought up again but seems lower priority
=> fix(up): `devservices up` will not restart supervisor if it is already running

devservices/commands/down.py, devservices/commands/foreground.py, devservices/commands/logs.py, devservices/commands/serve.py, devservices/commands/status.py, devservices/commands/up.py, devservices/configs/service_config.py, devservices/constants.py, devservices/utils/supervisor.py, testing/utils.py, tests/commands/test_down.py, tests/commands/test_foreground.py, tests/commands/test_list_services.py, tests/commands/test_logs.py, tests/commands/test_serve.py, tests/commands/test_status.py, tests/commands/test_up.py, tests/configs/test_service_config.py, tests/utils/test_supervisor.py
This moves previous programs.conf file definitions to config.yml. It allows for us to abstract default settings away from the user while keeping the config file more simple
Example `x-programs` block in config.yml:
```
x-programs:
devserver:
command: sentry devserver
taskworker:
command: sentry run taskworker --autoreload
taskworker-scheduler:
command: sentry run taskworker-scheduler
```
=> chore(config): Consolidate programs.conf file into config.yml

devservices/commands/up.py, tests/commands/test_up.py
This is a biased suggestion, but when I read the startup console logs:
```
Starting 'launchpad' in mode: 'default'
Retrieving dependencies
Pulling images
Pulled image for kafka
Starting kafka
Waiting for all containers to be healthy
kafka is healthy
launchpad started
```
it's not launchpad that is starting but rather launchpad's dependencies
=> chore(devservices): add 'dependencies' string within startup console logs

devservices/utils/docker.py, tests/utils/test_docker.py, tests/utils/test_docker_compose.py
If docker daemon not running, attempt to start it with `devenv colima start`
=> feat(docker): Auto start colima

devservices/commands/down.py, devservices/commands/up.py, devservices/main.py, devservices/utils/dependencies.py, devservices/utils/docker_compose.py, requirements.txt
This adds some basic logs, since we should dogfood our own product.
example logs: https://sentry.sentry.io/explore/logs/?guidedStep=3&logsFields=timestamp&logsFields=message&logsSortBys=-timestamp&project=4507946704961536&statsPeriod=30d
=> feat(logging): Add some basic logs
